[build-system]
requires = ['flit_core >=3.2,<4']
build-backend = 'flit_core.buildapi'

[project]
name = 'clashogram'
authors = [{name = 'Mehdi Sadeghi', email = 'mehdi@mehdix.org'}]
readme = 'README.rst'
license = {file = 'LICENSE.txt'}
requires-python = '>=3.10'
keywords = ['coc', 'telegram', 'clashofclans']
dynamic = ['version', 'description']
classifiers = [
    'Environment :: Console',
    'Natural Language :: Persian',
    'Natural Language :: English',
    'Development Status :: 4 - Beta',
    'Programming Language :: Python :: 3',
    'Intended Audience :: End Users/Desktop',
    'License :: OSI Approved :: MIT License']
dependencies = ['requests',
                'jdatetime',
                'pytz',
                'python-dateutil',
                'click']

[project.optional-dependencies]
test = ['pytest']
i18n = ['babel']

[project.urls]
Home = 'https://github.com/mehdisadeghi/clashogram'

[project.scripts]
clashogram = 'clashogram:main'

[tool.ruff]
line-length = 79
